name: Buster
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: make test
  build-deploy:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - run: make build-deploy
