name: php7.4-cli-alpine3.13
on:
  push:
    branches: [main]
    paths:
      - 'php7-alpine/**'
      - '.github/workflows/php7-alpine.yml'
jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    env:
      TOKEN: ${{ secrets.TOKEN }}
      USERNAME: ${{ secrets.USERNAME }}
      DOCKER_IMG: "rdok/php-docker:7.4-cli-alpine3.13"
      DOCKER_PATH: "php7-alpine"
    steps:
      - uses: actions/checkout@v2
      - run: docker build --tag "${DOCKER_IMG}" "${DOCKER_PATH}"
      - run: |
          echo "${TOKEN}" | docker login -u "${USERNAME}" --password-stdin
          docker image push "${DOCKER_IMG}"
      - run: docker logout
        if: ${{ always() }}
