name: php8.0-buster
defaults:
  run:
    working-directory: ./php8/buster
on:
  push:
    branches: [main]
    paths:
      - 'php8/buster/**'
      - '.github/workflows/php8-buster.yml'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make test
  build-deploy:
    runs-on: ubuntu-20.04
    needs: test
    env:
      TOKEN: ${{ secrets.TOKEN }}
      USERNAME: ${{ secrets.USERNAME }}
    steps:
      - uses: actions/checkout@v2
      - run: make build-deploy
