name: PHP8
on:
  push:
    branches: [ main ]
    paths:
      - 'php8-alpine/**'
      - '.github/workflows/php8-alpine.yml'
jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    env:
      TOKEN: ${{ secrets.TOKEN }}
      USERNAME: ${{ secrets.USERNAME }}
      IMG: 'rdok/php-docker:8.0-cli-alpine'
      PATH: 'php8-alpine'
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build --tag "${IMG}" "${PATH}"
          echo "${TOKEN}" | docker login -u "${USERNAME}" --password-stdin
          docker image push ${IMG}
          docker logout
