name: PHP8
on:
  push:
    branches: [ main ]
    paths:
      - 'php8-alpine/**'
      - '.github/workflows/php8-alpine.yml'
jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    env:
      TOKEN: ${{ secrets.TOKEN }}
      USERNAME: ${{ secrets.USERNAME }}
      DOCKER_IMG: "rdok/php-docker:8.0-cli-alpine"
      DOCKER_PATH: "php8-alpine"
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build --tag "${DOCKER_IMG}" "${DOCKER_PATH}"
          echo "${TOKEN}" | docker login -u "${USERNAME}" --password-stdin
          docker image push "${DOCKER_IMG}"
          docker logout
